ChatGpt:
  api_key: "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"
  Model: "TEXT_DAVINCI_003"
  token_length: 1024
  default_response: "&a机器人迷糊了"
autoChat:
  enable: true
  interval: 1

database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database