debug: false
ChatGpt:
  api_key: "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"
  Model: "TEXT_DAVINCI_003"
  token_length: 1024
  default_response: "&a机器人迷糊了"
  name: "ChatGpt"
  format: "&a%name%&8>>&c&l@%player_name%&f%text%"
autoChat:
  enable: true
  interval: 10
#玩家主动呼叫机器人
atBot:
  enable: true
  cool: 10
  prefix: "@%name%"
  condition: 'all [ money 100 points 100 perm vip ]'
  action: 'takeMoney 100 takePoints 100'
  deny: 'tell 您的金币或点券不足,或者正在冷却中...'
database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database